ifast:
  projectName: ifast
  projectRootURL: http://127.0.0.1:8088/
  demoMode: false
  jwt:
    userPrimaryKey: userId
    expireTokenKeyPrefix: ifast:expireToken
    expireTime: 7200000
    refreshTokenExpire: 86400000
  swagger:
    title: ifast接口文档
    description: 开发人员太懒，没有写描述
    contactName: Aron
    contactEmail: izenglong@163.com
    contactUrl: http://ifast.site/doc.html
    basePackage: com.ifast
    termsOfServiceUrl: ${ifast.projectRootURL}/docs.html
  shiro:
    jsessionidKey: SESSION
    sessionKeyPrefix: ifast:session
  oss:
    local: # 配置 localPath 启用本地上传（默认方式）
      localPath: upload
      rootURL: http://localhost/upload
    aliyun: # 配置 accessKeySecret 启用阿里云OSS
      isEnable: false
      accessKeyId:
      accessKeySecret:
      bucketName:
      # endpoint以深圳为例，其它region请按实际情况填写
      endpoint: http://oss-cn-shenzhen.aliyuncs.com
    qiniu: # 配置 accessKey 启用七牛云OSS
      isEnable: false
      accessKey:
      secretKey:
      bucket:
      accessURL:

logging:
  level:
    com.ifast: debug
    springfox.documentation: error
    org.springframework.web.servlet.mvc.method.annotation: error
    org.springframework.context.support: error
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tour?useUnicode=true&useSSL=false
    # 推荐utf8mb4编码以便支持表情字符，sys_log记录系统数据变动需要支持utf8mb4
    username: root
    password: 123456
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true